language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer install

script:
  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"

